language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - TEST_API_URL=http://develop.staging.api.datagami.net/
  - TEST_API_KEY=travisci
  - secure: OrecF5Nuwaq7gqohccXIPR8fCA0TlyM2ERTn1ETfJTL7B3k8CHiHi1k5TwTCuNc5K6wRmn+Lx2qNcNveisvBX6+2fiTBOHuD5vay+CNQEVLw0qqwsCYUG/2d53gpAeScN8hGCWx3bx0re6BHjb+ajVMFXTt4TkGa9zpqM5koavs=
