language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - TEST_API_URL=http://develop.staging.api.datagami.net/
  - TEST_API_KEY=travis
  - secure: D+3R5YucW1E/2HgNUZSrzhd1lKqP8d0YeZIu7vdl9ceQz1c0ovxFV1e36+2qmpls41IFwi7awyR6NshoxrrIRArA+cmMIPEQoJWkP+zAofimzWHQMdrfFvD/gzMziKfLwf+XrKCLJiPunMG67I3pEzEvFtnvxwOHzlC8IB964IE=
