language: node_js
node_js:
- '0.11'
- '0.10'
env:
  global:
  - TEST_API_URL=http://develop.staging.api.datagami.net/
  - TEST_API_KEY=travisci
  - secure: e0scSPlkcF9+S4pVsTCVyckc7feFfdDfmVwNnCFMujTA6mM3vKfs5+QL/Zj1ovymh2Zc+DJv+fiaONVjnp02LMl/DqQgJ1wk4HyQYo4vXQLz/710N1q2Ar0vyFkWqEZfiAHIsXjbFmLXbvmZ1SklyD1TRc5bHTM1w3IMioYlrnA=
